FROM mysql

ENV MYSQL_USER=qwer
ENV MYSQL_PASSWORD=qwer1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=dockerdb

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]