services:
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=dockerdb
    ports:
      - "3307:3306"

volumes:
  mysql-compose-volume: 